prompt --application/pages/page_00003
begin
--   Manifest
--     PAGE: 00003
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.5'
,p_default_workspace_id=>37849804862927571566
,p_default_application_id=>168290
,p_default_id_offset=>0
,p_default_owner=>'WKSP_SISTEMPARKIMI'
);
wwv_flow_imp_page.create_page(
 p_id=>3
,p_name=>'Lista e Automjeteve'
,p_alias=>'LISTA-AUTOMJETEVE'
,p_step_title=>'Lista e Automjeteve'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(38018846191503953091)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2531463326621247859
,p_plug_display_sequence=>10
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(38005191915980707976)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4072363345357175094
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(38018846880726953093)
,p_plug_name=>'Menaxhimi i Automjeteve'
,p_region_template_options=>'#DEFAULT#:t-IRR-region--hideHeader js-addHiddenHeadingRoleDesc'
,p_plug_template=>2100526641005906379
,p_plug_display_sequence=>10
,p_query_type=>'TABLE'
,p_query_table=>'AUTOMJETET'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_prn_page_header=>'Menaxhimi i Automjeteve'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(38018846939519953093)
,p_name=>'Menaxhimi i Automjeteve'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'A.HALILI2004@GMAIL.COM'
,p_internal_uid=>38018846939519953093
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(38018849926306953250)
,p_db_column_name=>'AUTOMJET_ID'
,p_display_order=>0
,p_is_primary_key=>'Y'
,p_column_identifier=>'A'
,p_column_label=>'Automjet ID'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(38018850396570953251)
,p_db_column_name=>'MARKA'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Marka'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(38018850779023953251)
,p_db_column_name=>'MODELI'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Modeli'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(38018851178790953252)
,p_db_column_name=>'NGJYRA'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Ngjyra'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(38018851579306953252)
,p_db_column_name=>'TARGA'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Targa'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(38018852089601953252)
,p_db_column_name=>'LLOJI_AUTOMJETIT'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Lloji Automjetit'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(38018852484845953253)
,p_db_column_name=>'KLIENT_ID'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Klient'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_rpt_named_lov=>wwv_flow_imp.id(38018849101211953248)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(38018852870386953253)
,p_db_column_name=>'DATA_REGJISTRIMIT'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Data Regjistrimit'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(38233079889568394381)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'382330799'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'AUTOMJET_ID:MARKA:MODELI:NGJYRA:TARGA:LLOJI_AUTOMJETIT:KLIENT_ID:DATA_REGJISTRIMIT'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(37974895740898885613)
,p_button_sequence=>20
,p_button_name=>'Automjet'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#:t-Button--iconLeft'
,p_button_template_id=>2082829544945815391
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Shto Automjet'
,p_button_redirect_url=>'f?p=&APP_ID.:6:&SESSION.::&DEBUG.:6::'
,p_icon_css_classes=>'fa-plus-square'
,p_grid_new_row=>'N'
,p_grid_new_column=>'N'
);
wwv_flow_imp.component_end;
end;
/
